
_PASS = [
        "Password",
        "Passcode",
        "Secret",
        "Key",
        "AccessCode",
        "SecurityPhrase",
        "AuthenticationToken",
        "PIN",
        "Passphrase",
        "SecureKey",
        "Cipher",
        "LockCode",
        "AuthenticationCode",
        "SecurePassword",
        "EncryptionKey",
        'HiddenKey',
        'Token',
    ]

_ERRORS = {
        -1000: 'CODE -1000: HumanError\nError code `{}` is not being used anymore.',
        -1: 'CODE -1: ImportantUserMessage\nPlease exercise caution when providing specific keyword arguments, depending on how the DataLoader is initialized. In case of any errors, you can utilize the \'no_method\' keyword to return all files as IO.textWrapper.',
        0: 'CODE 0: EmptyDataLoaderError]\nNo files were detected. Please initialize a DataLoader instance with validated file paths to proceed.',
        1: 'CODE 1: NoDundersOrDynamicError\n{!r} lacks support for dunder methods or DynamicDict capabilities. Kindly include the `dynamic` argument or utilize the `files` attribute to obtain files in generator format and attempt the operation anew.',
        7: 'CODE 7: SQLConfigCreation\nAn empty SQL .INI configuration file has been successfully created as `{!r}`.\n' \
            'Once you have made the necessary modifications, please re-run ConfigManager using the updated SQL configuration file to include encryption.\n',
        13: 'CODE 13: PermissionError\nYou do not have permission to access `{!r}`',
        17: 'CODE 17: AddingDataLoaderError\n`{!r}` is not an instance of {}.',
        18: 'CODE 18: AddingMessage\nDataLoader files are treated as a dictionary. Please be cautious if any file names are relevant when adding DataLoader objects.',
        100: 'CODE 100: UnicodeDecodeError\nThere was an encoding error when reading `{!r}`',
        102: 'CODE 102: JSONDecodeError\nFailed to decode JSON: `{!r}`. Position: {!r}. Line: {!r}. Column: {!r}.',
        150: 'CODE 150: InjectingFilesError\nRequires at least one valid directory to be injected.',
        200: 'CODE 200: DataLoaderAttributeError\n{!r} necessitates a valid file path. Please review all paths before initiating.',
        202: 'CODE 202: DataLoderAttributeError\nCannot specify both `ext_defaults` and `all_` attributes. Omit both and {!r} will use the following extensions by default:\n{!r}.',
        210: 'CODE 210: DefaultExtensionsError:\nAll provided extension{} are invalid: {!r}\nAll available extensions:\n{!r}',
        215: 'CODE 215: ExtensionsError:\nSkipping invalid extensions: `{!r}`',
        220: 'CODE 220: AddingFilesError:\nThe input must include at least one valid file path.',
        221: 'CODE 221: GetKeyError:\n`{!r}` is not a valid key. Did you mean `{!r}`?',
        222: 'CODE 222: NoKeyError:\nA key must be provided; otherwise, pass in None to return None.',
        223: 'CODE 223: NoItemError:\n`{!r}` was not found within the loaded files. Did you mean `{!r}`?',
        225: 'CODE 225: NoAttributeError:\n`{!r}` is not a valid attribute name. Did you mean `{!r}`?',
        227: 'CODE 227: GetAttributeError:\nUsing `__getitem__` is not suitable. File names with unique extensions have been identified. It is imperative to include the file extensions.',
        230: 'CODE 230: DataLoaderPathError:\nA valid path is required. If a path is provided, then the value of `{!r}` is considered invalid.\nError message: {!r}',
        303: 'CODE 303: ParserError\nParsing error for file `{!r}`',
        400: 'CODE 400: DtypeWarning\nThere are data type warnings for `{!r}`.\nConsider specifying data types with the dtype parameter',
        402: 'CODE 402: OSError\n`{!r}` obtained an OSError.\n{!r}',
        404: 'CODE 404: FileNotFoundError\nThe file `{!r}` does not exist.',
        500: 'CODE 500: Exception\nAn unexpected error occurred: `{!r}`',
        530: 'CODE 530: NoMethodFoundError\nUnable to identify a suitable loading method for `{!r}`. Please ensure that the file is accessible, is set to read or read-write only and is capable of being opened.',
        702: 'CODE 702: ExtensionTypeError\nCheck `{!r}` extensions and make sure it is relative to the extension loading method',
        607: 'CODE 607: EmptyDataError\n`{!r}` is an empty dataset. No columns to parse. File will be skipped.',
        707: 'CODE 707: PathTypeError\n`{!r}` is not valid. Must be an existing file, directory, or an absolute path.',
        800: 'CODE 800: AttributeError\nThe provided argument is not valid `{!r}`',
        870: 'CODE 870: ConfigDatabaseError\n`{!r}` is an unsupported database type.',
        880: 'CODE 880: NoConfigFileError\nA configuration file is required.',
        890: 'CODE 890: ConfigSectionsError\nNo sections were found for {!r}',
        899: 'CODE 899: ConfigValuesError\nNo values were found for {!r}',
        1000: 'CODE 1000: ConfigFileError\n`{!r}` is currently empty and only contains null values.\nPlease verify the contents of your configuration file before proceeding.',
        1001: 'CODE 1001: ConfigSectionError\n`{!r}` -> Spelling errors detected. Possible Sections based on arguments provided are as follows\n({!r})',
        1002: 'CODE 1002: ConfigEmptySectionError\n`{!r}`... was found but is currently empty and/or contains null values.\n',
        1003: 'CODE 1003: ConfigAttributeSectionError\nThe provided key sections `{!r}` are invalid. Please review the arguments being passed.',
}
