
_PASS = [
        "Password",
        "Passcode",
        "Secret",
        "Key",
        "AccessCode",
        "SecurityPhrase",
        "AuthenticationToken",
        "PIN",
        "Passphrase",
        "SecureKey",
        "Cipher",
        "LockCode",
        "AuthenticationCode",
        "SecurePassword",
        "EncryptionKey",
        'HiddenKey',
        'Token',
    ]

_ERRORS = {
        -1: '[CODE -1: HumanError]\nCheck if error code `{}` is still being used.',
        0: '[CODE 0: EmptyDataLoaderError]\nNo files were detected. Please initialize a DataLoader instance with validated file paths to proceed.',
        7: '[CODE 7: SQLConfigCreation]\nAn empty SQL .INI configuration file has been successfully created as `{}`.\n' \
            'Once you have made the necessary modifications, please re-run ConfigManager using the updated SQL configuration file to include encryption.\n',
        13: '[CODE 13: PermissionError]\nYou do not have permission to access `{}`',
        100: '[CODE 100: UnicodeDecodeError]\nThere was an encoding error when reading `{}`',
        102: '[CODE 102: JSONDecodeError]\nFailed to decode JSON: `{}`. Position: {}. Line: {}. Column: {}.',
        200: '[CODE 200: DataLoaderAttributeError]\n`{}` requires at least one argument to be provided.',
        202: '[CODE 202: DataLoderAttributeError]\nCannot specify both `ext_defaults` and `all_` attributes. Omit both and {} will use the following extensions by default:\n{}.',
        210: '[CODE 210: DefaultExtensionsError]:\nAll provided default extension{} are invalid:\n{}\nAll available extensions:\n{}',
        215: '[CODE 215: DefaultExtensionsError]:\nThe extensions provided are invalid and will be skipped: {}',
        220: '[CODE 220: AddingFilesError]:\nThe input must include at least one valid file path.',
        222: '[CODE 220: NoKeyError]:\nA specific argument is mandatory; otherwise, it will default to None if no default argument is provided.',
        230: '[CODE 230: DataLoaderPathError]:\nA valid path is required. If a path is provided, then the value of `{}` is considered invalid.\nError message: {}',
        303: '[CODE 303: ParserError]\nParsing error for file `{}`',
        400: '[CODE 400: DtypeWarning]\nThere are data type warnings for `{}`.\nConsider specifying data types with the dtype parameter',
        402: '[CODE 402: OSError]\n`{}` obtained an OSError.\n{}',
        404: '[CODE 404: FileNotFoundError]\nThe file `{}` does not exist.',
        500: '[CODE 500: Exception]\nAn unexpected error occurred: `{}`',
        530: '[CODE 530: NoMethodFoundError]\nUnable to identify a suitable loading method for `{}`. Please ensure that the file is accessible, is set to read or read-write only and is capable of being opened.',
        702: '[CODE 702: ExtensionTypeError]\nCheck `{}` extensions and make sure it is relative to the extension loading method',
        607: '[CODE 607: EmptyDataError]\n`{}` is an empty dataset. No columns to parse. File will be skipped.',
        707: '[CODE 707: PathTypeError]\n`{}` is not valid. Must be an existing file, directory, or an absolute path.',
        800: '[CODE 800: AttributeError]\nThe provided argument is not valid `{}`',
        870: '[CODE 870: ConfigDatabaseError]\n`{}` is an unsupported database type.',
        880: '[CODE 880: NoConfigFileError]\nA configuration file is required.',
        890: '[CODE 890: ConfigSectionsError]\nNo sections were found for {}',
        899: '[CODE 899: ConfigValuesError]\nNo values were found for {}',
        1000: '[CODE 1000: ConfigFileError]\n`{}` is currently empty and only contains null values.\nPlease verify the contents of your configuration file before proceeding.',
        1001: '[CODE 1001: ConfigSectionError]\n`{}` -> Spelling errors detected. Possible Sections based on arguments provided are as follows\n({})',
        1002: '[CODE 1002: ConfigEmptySectionError]\n`{}`... was found but is currently empty and/or contains null values.\n',
        1003: '[CODE 1003: ConfigAttributeSectionError]\nThe provided key sections `{}` are invalid. Please review the arguments being passed.',
}
