# pyblack.toml

[tool.black]
line-length = 120
pyi = "true"
skip-string-normalization = "true"
use-single-quotes = false
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
    | \.git
    | \.tox
    | \.venv
    | build
    | dist
)/
'''